version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

