"""Add qr_code_url to images

Revision ID: 2104e64f89cf
Revises: 7cfe77642ebd
Create Date: 2024-06-27 00:16:54.770218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2104e64f89cf'
down_revision: Union[str, None] = '7cfe77642ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('qr_code_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'qr_code_url')
    # ### end Alembic commands ###
