"""Imagas_tags v2

Revision ID: 2686e412417f
Revises: 9112ae947b0a
Create Date: 2024-06-27 23:03:21.742313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2686e412417f'
down_revision: Union[str, None] = '9112ae947b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_m2m_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('tags_images_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'images_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('images_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_images_id_fkey', 'tags', 'images', ['images_id'], ['id'])
    op.drop_table('image_m2m_tag')
    # ### end Alembic commands ###
