"""Fix 2.0 models.py

Revision ID: 2b221f4fda90
Revises: 85e0a7733bf5
Create Date: 2024-06-24 02:02:25.886171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b221f4fda90'
down_revision: Union[str, None] = '85e0a7733bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
