"""Fix 4.0 models.py

Revision ID: 394e3a2228bf
Revises: 5b87cb2ff226
Create Date: 2024-06-24 02:08:13.545581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394e3a2228bf'
down_revision: Union[str, None] = '5b87cb2ff226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
