"""Version_0.1.22

Revision ID: 3a908827c94d
Revises: 3219ab1b1b22
Create Date: 2024-07-02 00:22:29.381869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a908827c94d'
down_revision: Union[str, None] = '3219ab1b1b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'qr_code_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'qr_code_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
