"""Version_0.1.11

Revision ID: 5354ef7b8b8a
Revises: 2104e64f89cf
Create Date: 2024-06-28 17:44:16.049768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5354ef7b8b8a'
down_revision: Union[str, None] = '2104e64f89cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
