"""Fix 3.0 models.py

Revision ID: 5b87cb2ff226
Revises: 2b221f4fda90
Create Date: 2024-06-24 02:05:14.097108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b87cb2ff226'
down_revision: Union[str, None] = '2b221f4fda90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
