"""Version_0.1.2

Revision ID: 6d61ab5ebe44
Revises: d397c7bbb457
Create Date: 2024-06-21 21:21:49.173322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d61ab5ebe44'
down_revision: Union[str, None] = 'd397c7bbb457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
