"""added unique field to username

Revision ID: 7f08a7445663
Revises: 5da82e1c4883
Create Date: 2024-06-26 12:19:25.175292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f08a7445663'
down_revision: Union[str, None] = '5da82e1c4883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('images', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('images', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('images', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
