"""UPGRADE tables

Revision ID: 840c952f33cb
Revises: de6a57855a17
Create Date: 2024-06-23 20:44:21.422993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840c952f33cb'
down_revision: Union[str, None] = 'de6a57855a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('comments', 'images_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('comments_images_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'images', ['images_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'comment')
    op.drop_column('comments', 'updated_at')
    op.add_column('images', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('images', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('images', sa.Column('images_url', sa.String(length=255), nullable=False))
    op.add_column('images', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.alter_column('images', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'images', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('images', 'image')
    op.alter_column('tags', 'tag',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.add_column('users', sa.Column('blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked')
    op.alter_column('tags', 'tag',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.add_column('images', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.alter_column('images', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('images', 'owner_id')
    op.drop_column('images', 'images_url')
    op.drop_column('images', 'description')
    op.drop_column('images', 'title')
    op.add_column('comments', sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_images_id_fkey', 'comments', 'images', ['images_id'], ['id'])
    op.alter_column('comments', 'images_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
