"""Initial migration

Revision ID: 952a4a9d4ed8
Revises: aafeb16eee93
Create Date: 2024-06-22 00:39:16.144644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952a4a9d4ed8'
down_revision: Union[str, None] = 'aafeb16eee93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'crated_at')
    # ### end Alembic commands ###
