"""changed relation to m2m

Revision ID: 960b22845296
Revises: 8f19e298a5ba
Create Date: 2024-07-01 13:14:02.467274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960b22845296'
down_revision: Union[str, None] = '8f19e298a5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_tag',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'tag_id')
    )
    op.drop_constraint('tags_images_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'images_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('images_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_images_id_fkey', 'tags', 'images', ['images_id'], ['id'])
    op.drop_table('image_tag')
    # ### end Alembic commands ###
