"""Version_0.1.3

Revision ID: a3f2f26389e8
Revises: 6d61ab5ebe44
Create Date: 2024-06-21 21:30:34.950117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f2f26389e8'
down_revision: Union[str, None] = '6d61ab5ebe44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.alter_column('images', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'tags', ['tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.alter_column('images', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('roles')
    # ### end Alembic commands ###
