"""Version_0.1.7

Revision ID: d05c3ee5e765
Revises: 952a4a9d4ed8
Create Date: 2024-06-23 18:21:43.833680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05c3ee5e765'
down_revision: Union[str, None] = '952a4a9d4ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
