"""make description and title optional

Revision ID: d21087a4ebe4
Revises: 394e3a2228bf
Create Date: 2024-06-24 11:42:50.156376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21087a4ebe4'
down_revision: Union[str, None] = '394e3a2228bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('images', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('images', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
