"""Version_0.1.23

Revision ID: fd74b452a791
Revises: 3a908827c94d
Create Date: 2024-07-02 00:28:07.627525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd74b452a791'
down_revision: Union[str, None] = '3a908827c94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'qr_code_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'qr_code_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
